# Axis datasets

ax_continuity_state:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_STATE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_STATE_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_distance:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_tmp:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_%(tag)s.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(tag)s_%(row)02d_%(col)02d
    extension: .tif

ax_continuity:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d/CONTINUITY
  filename: LANDCOVER_CONTINUITY_MAP.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_MAP_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_tagged:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d/CONTINUITY
  filename: LANDCOVER_CONTINUITY_%(tag)s.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(tag)s_%(row)02d_%(col)02d
    extension: .tif

# Network datasets

continuity_state:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: NETWORK/TEMP
  filename: LANDCOVER_CONTINUITY_STATE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_STATE_%(row)02d_%(col)02d
    extension: .tif

continuity_distance:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: NETWORK/TEMP
  filename: LANDCOVER_CONTINUITY_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

continuity_tmp:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: NETWORK/TEMP
  filename: LANDCOVER_CONTINUITY_%(tag)s.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(tag)s_%(row)02d_%(col)02d
    extension: .tif

continuity:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: NETWORK/CONTINUITY
  filename: LANDCOVER_CONTINUITY_MAP.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_MAP_%(row)02d_%(col)02d
    extension: .tif

continuity_tagged:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: NETWORK/CONTINUITY
  filename: LANDCOVER_CONTINUITY_%(tag)s.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(tag)s_%(row)02d_%(col)02d
    extension: .tif

# ax_continuity:
#   description: |
#     Landcover continuity map
#   type: raster
#   group: corridor
#   status: final
#   subdir: AXES/AX%(axis)04d/CONTINUITY
#   filename: LANDCOVER_CONTINUITY.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(row)02d_%(col)02d
#     extension: .tif

# ax_continuity_variant:
#   description: |
#     Landcover continuity map (Variants)
#   type: raster
#   group: corridor
#   status: final
#   subdir: AXES/AX%(axis)04d/CONTINUITY
#   filename: LANDCOVER_CONTINUITY_%(variant)s.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(variant)s_%(row)02d_%(col)02d
#     extension: .tif

# ax_continuity_remapped:
#   description: |
#     Interpreted landcover continuity map
#   type: raster
#   group: corridor
#   status: final
#   subdir: AXES/AX%(axis)04d/CONTINUITY
#   filename: LANDCOVER_CONTINUITY_FINAL.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_FINAL_%(row)02d_%(col)02d
#     extension: .tif

# ax_continuity_variant_remapped:
#   description: |
#     Interpreted landcover continuity map (Variants)
#   type: raster
#   group: corridor
#   status: final
#   subdir: AXES/AX%(axis)04d/CONTINUITY
#   filename: LANDCOVER_CONTINUITY_%(variant)s_FINAL.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(variant)s_FINAL_%(row)02d_%(col)02d
#     extension: .tif

# ax_continuity_map_final:
#   description: |
#     Interpreted landcover continuity map (Variants)
#   type: raster
#   group: corridor
#   status: final
#   subdir: AXES/AX%(axis)04d
#   filename: LANDCOVER_CONTINUITY_%(variant)s_FINAL.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(variant)s_FINAL_%(row)02d_%(col)02d
#     extension: .tif

# continuity_raw:
#   description: |
#     Landcover continuity map
#   type: raster
#   group: corridor
#   status: final
#   subdir: NETWORK/CONTINUITY
#   filename: LANDCOVER_CONTINUITY.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_RAW_%(row)02d_%(col)02d
#     extension: .tif

# continuity_state:
#   description: |
#     Landcover continuity map
#   type: raster
#   group: corridor
#   status: temporary
#   subdir: NETWORK/TEMP
#   filename: LANDCOVER_CONTINUITY_STATE.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_STATE_%(row)02d_%(col)02d
#     extension: .tif

# continuity_distance:
#   description: |
#     Landcover continuity map
#   type: raster
#   group: corridor
#   status: temporary
#   subdir: NETWORK/TEMP
#   filename: LANDCOVER_CONTINUITY_DISTANCE.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_DISTANCE_%(row)02d_%(col)02d
#     extension: .tif

# continuity_variant_raw:
#   description: |
#     Landcover continuity map (Variants)
#   type: raster
#   group: corridor
#   status: final
#   subdir: NETWORK/CONTINUITY
#   filename: LANDCOVER_CONTINUITY_RAW_%(variant)s.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_RAW_%(variant)s_%(row)02d_%(col)02d
#     extension: .tif

# continuity_final:
#   description: |
#     Interpreted landcover continuity map
#   type: raster
#   group: corridor
#   status: final
#   subdir: NETWORK/CONTINUITY
#   filename: LANDCOVER_CONTINUITY.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(row)02d_%(col)02d
#     extension: .tif

# continuity_variant_final:
#   description: |
#     Interpreted landcover continuity map (Variants)
#   type: raster
#   group: corridor
#   status: final
#   subdir: NETWORK/CONTINUITY
#   filename: LANDCOVER_CONTINUITY_%(variant)s.vrt
#   tiles:
#     tileset: landcover
#     template: LANDCOVER_CONTINUITY_%(variant)s_%(row)02d_%(col)02d
#     extension: .tif

continuity_map_final:
  description: |
    Interpreted landcover continuity map (Variants)
  type: raster
  group: corridor
  status: final
  subdir: GLOBAL/CONTINUITY
  filename: LANDCOVER_CONTINUITY_%(variant)s_FINAL.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(variant)s_FINAL_%(row)02d_%(col)02d
    extension: .tif