# Per axis datasets
# Corridor descriptors

ax_shortest_height:
  description: |
    Height above stream talweg following shortest path
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SHORTEST_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: SHORTEST_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_shortest_distance:
  description: |
    Shortest path distance to stream talweg
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: SHORTEST_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: SHORTEST_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_shortest_state:
  description: |
    Temporary processing state for shortest height,
    saved between iterations
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: SHORTEST_STATE.vrt
  tiles:
    tileset: landcover
    template: SHORTEST_STATE_%(row)02d_%(col)02d
    extension: .tif

ax_continuity:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: LANDCOVER_CONTINUITY.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_state:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_STATE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_STATE_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_distance:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_variant:
  description: |
    Landcover continuity map (Variants)
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: LANDCOVER_CONTINUITY_%(variant)s.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(variant)s_%(row)02d_%(col)02d
    extension: .tif

ax_valley_mask:
  description: |
    Valley mask from nearest height raster
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: VALLEY_MASK.vrt
  tiles:
    tileset: landcover
    template: VALLEY_MASK_%(row)02d_%(col)02d
    extension: .tif

ax_valley_mask_refined:
  description: |
    Valley mask from nearest height raster
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_MASK2.vrt
  tiles:
    tileset: landcover
    template: VALLEY_MASK2_%(row)02d_%(col)02d
    extension: .tif

ax_valley_height_mask:
  description: |
    Valley mask from valley height raster
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_HEIGHT_MASK.vrt
  tiles:
    tileset: landcover
    template: VALLEY_HEIGHT_MASK_%(row)02d_%(col)02d
    extension: .tif

ax_valley_height_mask_c0:
  description: |
    Valley mask from valley height raster
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_HEIGHT_MASK_C0.vrt
  tiles:
    tileset: landcover
    template: VALLEY_HEIGHT_MASK_C0_%(row)02d_%(col)02d
    extension: .tif

ax_corridor_mask:
  description: |
    Corridor mask from landcover continuity
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: CORRIDOR_MASK.vrt
  tiles:
    tileset: landcover
    template: CORRIDOR_MASK_%(row)02d_%(col)02d
    extension: .tif

ax_natural_corridor:
  description: |
    Natural corridor in continuity with river channel
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: NATURAL_CORRIDOR.vrt
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_%(row)02d_%(col)02d
    extension: .tif

ax_natural_corridor_state:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: NATURAL_CORRIDOR_STATE.vrt
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_STATE_%(row)02d_%(col)02d
    extension: .tif

ax_natural_corridor_distance:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: LANDCOVER_CONTINUITY_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_valley_bottom_boundary:
    description: |
      Pseudo valley bottom boundary,
      calculated from medial axis and measured valley bottom width
    type: linestring
    group: corridor
    status: final
    subdir: AXES/AX%(axis)04d
    filename: VALLEY_BOTTOM_BOUNDARY.shp

ax_swath_axes:
  description: |
    Spatial unit (swath) distance axis
    (orthogonal to reference axis)
  type: linestring
  subdir: AXES/AX%(axis)04d/REF
  filename: SWATH_AXIS.shp

ax_buffer_mask:
  description: |
    Buffer area calculated from axis active channel,
    based on landcover continuity classes.
    1 = active channel
    2 = buffer area within buffer width from active channel
    0 = elsewhere
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_MASK.vrt
  tiles:
    tileset: landcover
    template: BUFFER_MASK_%(row)02d_%(col)02d
    extension: .tif

ax_buffer_distance:
  description: |
    Distance from axis active channel,
    based on landcover continuity classes
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: BUFFER_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_buffer_profile:
  description: |
    Discrete spatial units (ie. slices of buffer area)
    along reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_PROFILE.vrt
  tiles:
    tileset: landcover
    template: BUFFER_PROFILE_%(row)02d_%(col)02d
    extension: .tif

ax_subgrid_profile:
  description: |
    SubGrid Profile
  type: point
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SUBGRID_PROFILE.shp

ax_subgrid_watershed:
  description: |
    SubGrid Profile Sample Watershed
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SUBGRID_WATERSHED.vrt
  tiles:
    tileset: landcover
    template: SUBGRID_WATERSHED_%(row)02d_%(col)02d
    extension: .tif