# tile coverage

ax_tiles:
  description: |
    List of tiles intersecting given axis
    (TODO remove entry)
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TILES.csv

ax_flow_tiles:
  description: |
    List of tiles intersecting flow height raster
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: FLOW_TILES.csv

ax_shortest_tiles:
  description: |
    List of tiles in ax_shortest_height dataset
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SHORTEST_TILES.csv