# Mapped hydrography

stream-network-cartography-in:
  description: |
    Stream network derived from cartography
    (input dataset)
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/INPUT
  filename: REFERENTIEL_HYDRO.shp

# stream-network-cartography:
#   description: |
#     Stream network derived from cartography
#     with sources attributes and updated HACK and LENAXIS fields
#   type: linestring
#   group: hydrography
#   status: input
#   subdir: GLOBAL/REFHYDRO
#   filename: REFERENTIEL_HYDRO.shp

stream-network-cartography-buffered:
  description: |
    Stream network derived from cartography buffered 
  type: polygon
  group: hydrography
  status: temporary
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_BUF.gpkg

stream-network-cartography-backup:
  description: |
    Stream network derived from cartography
    with sources attributes and updated HACK and LENAXIS fields
  type: linestring
  group: hydrography
  status: backup
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_BAK.shp

sources-cartography-in:
  description: |
    Stream network sources from cartography
    (input dataset)
  type: point
  group: hydrography
  status: input
  subdir: GLOBAL/INPUT
  filename: SOURCES.shp

network-cartography-gpkg:
  description: |
    Stream network derived from cartography
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO.gpkg

network-cartography-ordered:
  description: |
    Stream network derived from cartography,
    with updated AXIS, HACK and LENAXIS fields
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_ORDERED.shp

network-cartography-ready:
  description: |
    Stream network derived from cartography,
    working selection, aggregated by axis,
    measured from outlet
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO.shp

sources-cartography:
  description: |
    Stream network sources from cartography,
    working selection
  type: point
  group: hydrography
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: SOURCES.shp

outlets-cartography:
  description: |
    Stream network outlets from cartography,
    working selection
  type: point
  group: hydrography
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: OUTLETS.shp

river-network:
  description: |
    Stream network derived from cartography,
    connected segments, not aggregated
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: TRON_CDE_BDT.shp

river-network-agg:
  description: |
    Stream network derived from cartography,
    working selection, aggregated by axis,
    measured from outlet
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO.shp

river-network-sources:
  description: |
    Stream network sources from cartography,
    working selection
  type: point
  group: hydrography
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: SOURCES.gpkg

river-network-outlets:
  description: |
    Stream network outlets from cartography,
    working selection
  type: point
  group: hydrography
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: OUTLETS.shp

river-network-gpkg:
  description: |
    Stream network derived from cartography
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO.gpkg

river-network-ordered:
  description: |
    Stream network derived from cartography,
    with updated AXIS, HACK and LENAXIS fields
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_ORDERED.shp

hydrography-strahler-fieldbuf:
  description: |
    reference stream network with strahler order and buffer field to compute buffer before burn DEM
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_STRAHLER_FIELDBUF.gpkg

hydrography-strahler-fieldbuf-complete:
  description: |
    reference stream network with strahler order and buffer field completed to compute buffer before burn DEM
  type: linestring
  group: hydrography
  status: input
  subdir: GLOBAL/REFHYDRO
  filename: REFERENTIEL_HYDRO_STRAHLER_FIELDBUF_COMPLETE.gpkg