# Per axis datasets
# Metrology raster support and swath units definition
# raster measure and distance

ax_axis_mask:
  description: |
    Axis data mask
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: AXIS_MASK.vrt
  tiles:
    tileset: landcover
    template: AXIS_MASK_%(row)02d_%(col)02d
    extension: .tif
  
ax_axis_distance:
  description: |
    Distance to reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d/MEASURE
  filename: AXIS_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: AXIS_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_axis_measure:
  description: |
    Location (measure) along reference axis
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/MEASURE
  filename: AXIS_MEASURE.vrt
  tiles:
    tileset: landcover
    template: AXIS_MEASURE_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_distance:
  description: |
    Distance to mapped talweg
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/MEASURE
  filename: TALWEG_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: TALWEG_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_measure:
  description: |
    Location (measure) along cartography talweg
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/MEASURE
  filename: TALWEG_MEASURE.vrt
  tiles:
    tileset: landcover
    template: TALWEG_MEASURE_%(row)02d_%(col)02d
    extension: .tif

ax_medialaxis_distance:
  description: |
    Distance to reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: AXIS_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: MEDIALAXIS_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_medialaxis_measure:
  description: |
    Location (measure) along reference axis
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: MEDIALAXIS_MEASURE.vrt
  tiles:
    tileset: landcover
    template: MEDIALAXIS_MEASURE_%(row)02d_%(col)02d
    extension: .tif

talweg_segments:
  description: |
    Talweg segments
  type: linestring
  group: measure
  status: final
  subdir: NETWORK/CARTO
  filename: TALWEG_SEGMENTS.shp

talweg_segments:
  description: |
    Talweg segments
  type: linestring
  group: measure
  status: final
  subdir: AXES/AX%(axis)04d/CARTO
  filename: TALWEG_SEGMENTS.shp