# Metrics and output files

ax_swath_elevation:
  description: |
    Elevation swath
  type: npz
  group: metrics
  subdir: AXES/AX%(axis)04d/SWATH/ELEVATION
  filename: SWATH_ELEVATION_%(gid)04d.npz

ax_swath_landcover:
  description: |
    Landcover swath
  type: npz
  group: metrics
  subdir: AXES/AX%(axis)04d/SWATH/LANDCOVER
  filename: SWATH_ELEVATION_%(gid)04d_%(subset)s.npz

ax_swath_valleybottom:
  description: |
    Landcover swath
  type: npz
  group: metrics
  subdir: AXES/AX%(axis)04d/SWATH/VALLEYBOTTOM
  filename: SWATH_VALLEYBOTTOM_%(gid)04d.npz

ax_swath_elevation_pack:
  description: |
    Elevation Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: ELEVATION_SWATH_PROFILES.nc

ax_swath_landcover_pack:
  description: |
    LandCover Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_SWATH_PROFILES_%(subset)s.nc

metrics_talweg:
  description: |
    Talweg related metrics by valley swath unit
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: TALWEG_RELATED.nc

metrics_planform:
  description: |
    Talweg shift and position relative to reference axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM.nc

metrics_long_profile:
  description: |
    Long Profile Metrics:
    slopes, drainage area
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LONG_PROFILE.nc

metrics_valleybottom_width:
  description: |
    Valley bottom width and swath areas
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: VALLEY_BOTTOM_WIDTH.nc

metrics_fcw:
  description: |
    Fluvial Corridor Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: FLUVIAL_CORRIDOR_WIDTH.nc

metrics_lcw:
  description: |
    LandCover Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH.nc

metrics_lcw_variant:
  description: |
    LandCover Width (Variants)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH_%(variant)s.nc

metrics_watershed:
  description: |
    Watershed Metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WATERSHED_%(subset)s.nc

pdf_ax_swath_elevation:
  description: |
    Elevation swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_swath_landcover:
  description: |
    Landcover swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_landcover_profile:
  description: |
    Landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LANDCOVER_PROFILE_%(variant)s.pdf

pdf_ax_leftright_profile:
  description: |
    Left bank/right bank landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LEFTRIGHT_PROFILE_%(variant)s.pdf

pdf_ax_watershed_profile:
  description: |
    Watershed Profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/WATERSHED
  filename: WATERSHED_PROFILE_%(variable)s_W%(width).0f.pdf