# Metrics and output files

metrics_hypsometry_global:
  description:
    Hypsometry (distribution of elevations)
  type: netcdf
  group: metrics
  status: final
  subdir: GLOBAL/METRICS
  filename: HYPSOMETRY.nc

metrics_hypsometry:
  description:
    Subwatershed's hypsometry (distribution of elevations)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: HYPSOMETRY.nc

metrics_drainage_area:
  description: |
    Upstream drainage area calculated from DEM
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: DRAINAGE_AREA.nc

metrics_drainage_area_sw:
  description: |
    Upstream drainage area calculated from DEM
  type: netcdf
  group: metrics
  status: temporary
  subdir: AXES/AX%(axis)04d/METRICS
  filename: DRAINAGE_AREA_SW.nc

metrics_talweg:
  description: |
    Talweg related metrics by valley swath unit
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: MISC_TALWEG.nc

metrics_planform:
  description: |
    Talweg shift and position relative to reference axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM.nc

metrics_planform_refaxis:
  description: |
    Talweg shift and position relative to reference axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM_REFAXIS.nc

metrics_planform_planaxis:
  description: |
    Talweg shift and position relative to reference axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM_PLANAXIS.nc

# metrics_long_profile:
#   description: |
#     Long Profile Metrics:
#     slopes, drainage area
#   type: netcdf
#   group: metrics
#   status: final
#   subdir: AXES/AX%(axis)04d/METRICS
#   filename: LONG_PROFILE.nc

metrics_talweg_points:
  description: |
    Talweg (x, y, z)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: TALWEG_POINTS.nc

metrics_refaxis_points:
  description: |
    Refaxis (x, y, z)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: REFAXIS_POINTS.nc

metrics_elevation_profile:
  description: |
    Elevation profile
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: ELEVATION_PROFILE.nc

metrics_gradient_index:
  description: |
    Elevation profile
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: GRADIENT_INDEX.nc

metrics_talweg_elevation:
  description: |
    Talweg elevation (projected on elevation profile)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: TALWEG_ELEVATION.nc

metrics_talweg_length:
  description: |
    swath-intercepted talweg length
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: TALWEG_LENGTH.nc

metrics_planform_amplitude:
  description: |
    Planform amplitude (per swath interpolation)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM_AMPLITUDE.nc

metrics_planform_amplitude_sw:
  description: |
    Planform amplitude (per swath interpolation)
  type: netcdf
  group: metrics
  status: temporary
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM_AMPLITUDE_SW.nc

metrics_planform_amplitude_raw:
  description: |
    Planform amplitude (measured along talweg)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: PLANFORM_AMPLITUDE_RAW.nc

metrics_width_valley_bottom:
  description: |
    Valley bottom width,
    calculated from medial axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WIDTH_VALLEY_BOTTOM.nc

metrics_width_valley_bottom_tagged:
  description: |
    Valley bottom width,
    calculated from medial axis
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WIDTH_VALLEY_BOTTOM_%(tag)s.nc

metrics_width_corridor:
  description: |
    Corridor synthetic widths
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WIDTH_CORRIDOR.nc

# metrics_fcw:
#   description: |
#     Fluvial Corridor Width
#   type: netcdf
#   group: metrics
#   status: final
#   subdir: AXES/AX%(axis)04d/METRICS
#   filename: FLUVIAL_CORRIDOR_WIDTH.nc

# metrics_lcw:
#   description: |
#     LandCover Width
#   type: netcdf
#   group: metrics
#   status: final
#   subdir: AXES/AX%(axis)04d/METRICS
#   filename: LANDCOVER_WIDTH.nc

metrics_width_landcover:
  description: |
    LandCover Width (Variants)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WIDTH_LANDCOVER.nc

metrics_width_continuity:
  description: |
    LandCover Width (Variants)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WIDTH_CONTINUITY_%(tag)s.nc

metrics_watershed:
  description: |
    Watershed Metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WATERSHED_%(subset)s.nc

metrics_floodplain_height:
  description: |
    River profile metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: HEIGHT_FLOODPLAIN.nc

metrics_river_profile:
  description: |
    River profile metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: RIVER_PROFILE.nc

metrics_river_profile_tagged:
  description: |
    River profile metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: RIVER_PROFILE_%(tag)s.nc

elevation_profile_valley_bottom:
  description: |
    Valley bottom elevation profile (based on swath profiles)
  type: netcdf
  group: metrology
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: ELEVATION_VALLEY_BOTTOM.shp