# Metrics and output files

ax_swath_elevation_pack:
  description: |
    Elevation Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: ELEVATION_SWATH_PROFILES.nc

ax_swath_landcover_pack:
  description: |
    LandCover Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_SWATH_PROFILES_%(subset)s.nc

metrics_talweg_height:
  description: |
    Talweg height relative to valley floor
    by valley swath unit
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: TALWEG_HEIGHT.nc

metrics_long_profile:
  description: |
    Long Profile Metrics:
    slopes, drainage area
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LONG_PROFILE.nc

metrics_fcw:
  description: |
    Fluvial Corridor Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: FLUVIAL_CORRIDOR_WIDTH.nc

metrics_lcw:
  description: |
    LandCover Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH.nc

metrics_lcw_variant:
  description: |
    LandCover Width (Variants)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH_%(variant)s.nc

metrics_watershed:
  description: |
    Watershed Metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WATERSHED_%(subset)s.nc

pdf_ax_swath_elevation:
  description: |
    Elevation swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_swath_landcover:
  description: |
    Landcover swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_landcover_profile:
  description: |
    Landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LANDCOVER_PROFILE_%(variant)s.pdf

pdf_ax_leftright_profile:
  description: |
    Left bank/right bank landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LEFTRIGHT_PROFILE_%(variant)s.pdf

pdf_ax_watershed_profile:
  description: |
    Watershed Profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/WATERSHED
  filename: WATERSHED_PROFILE_%(variable)s_W%(width).0f.pdf