planform_inflection_points:
  description: |
    planform inflection points
  type: point
  group: planform
  status: final
  subdir: NETWORK/PLANFORM
  filename: INFLECTION_POINTS.shp

planform_axis_segments:
  description: |
    planform axis passing through inflection points,
    segments between inflection points
  type: linestring
  group: planform
  status: final
  subdir: NETWORK/PLANFORM
  filename: PLANFORM_AXIS_SEGMENTS.shp

planform_axis:
  description: |
    planform axis passing through inflection points
    (concatenated and smoothed)
  type: linestring
  group: planform
  status: final
  subdir: NETWORK/PLANFORM
  filename: PLANFORM_AXIS.shp

planform_segments:
  description: |
    segments between inflection points
  type: linestring
  group: planform
  status: final
  subdir: NETWORK/PLANFORM
  filename: SEGMENTS.shp

amplitude_stems:
  description: |
    maximum amplitude stems
  type: linestring
  group: planform
  status: final
  subdir: NETWORK/PLANFORM
  filename: AMPLITUDE.shp

planform_basic_metrics:
  description: |
    planform basic descriptors :
    shift, curvature and direction angle phi
  type: netcdf
  group: planform
  status: final
  subdir: NETWORK/METRICS
  filename: PLANFORM_%(refaxis)s.nc