# reference objects

refaxis:
  description: |
    Reference axis (global dataset)
  type: linestring
  group: reference
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: REFAXIS.shp

ax_refaxis:
  description: |
    Reference axis
  type: linestring
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: REFAXIS.shp

ax_talweg:
  description: |
    Mapped river network talweg (axis subset)
  type: linestring
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: TALWEG.shp

ax_drainage_network:
  description: |
    Theoretical stream network (axis subset)
  type: linestring
  group: reference
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DRAINAGE.shp

ax_medialaxis:
  description: |
    Valley medial axis
  type: linestring
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: MEDIAL_AXIS.shp

ax_medialaxis_simplified:
  description: |
    Valley medial axis
  type: linestring
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: MEDIAL_AXIS_SIMPL.shp
