# Per axis datasets
# Metrology raster support and swath units definition

refaxis:
  description: |
    Reference axis (global dataset)
  type: linestring
  group: spatial reference
  status: final
  subdir: GLOBAL/REFHYDRO
  filename: REFAXIS.shp

ax_tiles:
  description: |
    List of tiles intersecting given axis
    (TODO remove entry)
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TILES.csv

ax_flow_tiles:
  description: |
    List of tiles intersecting flow height raster
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: FLOW_TILES.csv

ax_talweg:
  description: |
    Mapped river network talweg (axis subset)
  type: linestring
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: TALWEG.shp

ax_refaxis:
  description: |
    Reference axis
  type: linestring
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: REFAXIS.shp

ax_valley_medialaxis:
  description: |
    Valley medial axis
  type: linestring
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: VALLEY_MEDIAL_AXIS.shp

ax_drainage_network:
  description: |
    Theoretical stream network (axis subset)
  type: linestring
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DRAINAGE.shp
  
ax_axis_distance:
  description: |
    Distance to reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: AXIS_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: AXIS_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_axis_measure:
  description: |
    Location (measure) along reference axis
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: AXIS_MEASURE.vrt
  tiles:
    tileset: landcover
    template: AXIS_MEASURE_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_distance:
  description: |
    Distance to mapped talweg
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TALWEG_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: TALWEG_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_measure:
  description: |
    Location (measure) along cartography talweg
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TALWEG_MEASURE.vrt
  tiles:
    tileset: landcover
    template: TALWEG_MEASURE_%(row)02d_%(col)02d
    extension: .tif

ax_valley_swaths:
  description: |
    Valley bottom longitudinal units
    (raster intermediate result)
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: VALLEY_SWATHS.vrt
  tiles:
    tileset: landcover
    template: VALLEY_SWATHS_%(row)02d_%(col)02d
    extension: .tif

ax_valley_swaths_polygons:
  description: |
    Valleu bottom longitudinal units
  type: polygon
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: VALLEY_SWATHS.shp
  tiles:
    tileset: landcover
    template: VALLEY_SWATHS_%(row)02d_%(col)02d
    extension: .shp

ax_valley_swaths_defs:
  description: |
    coordinate and bounds of valley bottom
    spatial units (after disaggregation)
  type: netcdf
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: VALLEY_SWATHS.nc

ax_corridor_swaths:
  description: |
    Natural corridor longitudinal units
    (raster intermediate result)
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: CORRIDOR_SWATHS.vrt
  tiles:
    tileset: landcover
    template: CORRIDOR_SWATHS_%(row)02d_%(col)02d
    extension: .tif

ax_corridor_swaths_polygons:
  description: |
    Natural corridor longitudinal units
  type: polygon
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: CORRIDOR_SWATHS.shp
  tiles:
    tileset: landcover
    template: CORRIDOR_SWATHS_%(row)02d_%(col)02d
    extension: .shp

ax_corridor_swaths_defs:
  description: |
    coordinate and bounds of fluvial corridor
    spatial units (after disaggregation)
  type: netcdf
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: CORRIDOR_SWATHS.nc

ax_natural_corridor_swaths:
  description: |
    Natural corridor longitudinal units
    (raster intermediate result)
    TODO duplicate of ax_swaths, to be removed
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: NATURAL_CORRIDOR_UNITS.vrt
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_UNITS_%(row)02d_%(col)02d
    extension: .tif

ax_natural_corridor_swaths_polygons:
  description: |
    Natural corridor longitudinal units
  type: polygon
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: NATURAL_CORRIDOR_UNITS.shp
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_UNITS_%(row)02d_%(col)02d
    extension: .shp

ax_dgo:
  description: |
    Spatial units discretization
    TODO duplicate of ax_swaths, to be removed
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_dgo_parts:
  description: |
    Spatial units polygons, extracted from measure raster
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO_PARTS.shp
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .shp

ax_dgo_vector:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
    TODO duplicate of ax_swath_polygons, to be removed
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp

ax_swaths:
  description: |
    Spatial units discretization
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_swath_polygons:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp


