# swaths

ax_valley_swaths:
  description: |
    Valley bottom longitudinal units
    (raster intermediate result)
  type: raster
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: VALLEY_SWATHS.vrt
  tiles:
    tileset: landcover
    template: VALLEY_SWATHS_%(row)02d_%(col)02d
    extension: .tif

ax_valley_swaths_polygons:
  description: |
    Valley bottom longitudinal units
  type: polygon
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: VALLEY_SWATHS.shp
  tiles:
    tileset: landcover
    template: VALLEY_SWATHS_%(row)02d_%(col)02d
    extension: .shp

ax_valley_swaths_bounds:
  description: |
    coordinate and bounds of valley bottom
    spatial units (after disaggregation)
  type: netcdf
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: VALLEY_SWATH_BOUNDS.nc

ax_corridor_swaths:
  description: |
    Natural corridor longitudinal units
    (raster intermediate result)
  type: raster
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: CORRIDOR_SWATHS.vrt
  tiles:
    tileset: landcover
    template: CORRIDOR_SWATHS_%(row)02d_%(col)02d
    extension: .tif

ax_corridor_swaths_polygons:
  description: |
    Natural corridor longitudinal units
  type: polygon
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: CORRIDOR_SWATHS.shp
  tiles:
    tileset: landcover
    template: CORRIDOR_SWATHS_%(row)02d_%(col)02d
    extension: .shp

ax_corridor_swaths_bounds:
  description: |
    coordinate and bounds of fluvial corridor
    spatial units (after disaggregation)
  type: netcdf
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: CORRIDOR_SWATH_BOUNDS.nc

ax_natural_corridor_swaths:
  description: |
    Natural corridor longitudinal units
    (raster intermediate result)
    TODO duplicate of ax_swaths, to be removed
  type: raster
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/TEMP
  filename: NATURAL_CORRIDOR_UNITS.vrt
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_UNITS_%(row)02d_%(col)02d
    extension: .tif

ax_natural_corridor_swaths_polygons:
  description: |
    Natural corridor longitudinal units
  type: polygon
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: NATURAL_CORRIDOR_UNITS.shp
  tiles:
    tileset: landcover
    template: NATURAL_CORRIDOR_UNITS_%(row)02d_%(col)02d
    extension: .shp

ax_dgo:
  description: |
    Spatial units discretization
    TODO duplicate of ax_swaths, to be removed
  type: raster
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_dgo_parts:
  description: |
    Spatial units polygons, extracted from measure raster
  type: polygon
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO_PARTS.shp
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .shp

ax_dgo_vector:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
    TODO duplicate of ax_swath_polygons, to be removed
  type: polygon
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp

ax_swaths:
  description: |
    Spatial units discretization
  type: raster
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_swath_polygons:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
  type: polygon
  group: reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp

ax_swath_polygons_vb_simplified:
  description: |
    Valley bottom (floodplain) longitudinal units,
    simplified and smoothed for display
  type: polygon
  group: reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: VALLEY_SWATHS_SIMPL.shp

ax_swath_elevation_npz:
  description: |
    Elevation swath
  type: npz
  group: metrics
  status: temporary
  subdir: AXES/AX%(axis)04d/SWATH/ELEVATION
  filename: SWATH_ELEVATION_%(gid)04d.npz

ax_swath_landcover_npz:
  description: |
    Landcover swath
  type: npz
  group: metrics
  status: temporary
  subdir: AXES/AX%(axis)04d/SWATH/LANDCOVER
  filename: SWATH_LANDCOVER_%(gid)04d_%(subset)s.npz

ax_swath_valleybottom_npz:
  description: |
    Landcover swath
  type: npz
  group: metrics
  status: temporary
  subdir: AXES/AX%(axis)04d/SWATH/VALLEYBOTTOM
  filename: SWATH_VALLEYBOTTOM_%(gid)04d.npz

swath_elevation:
  description: |
    Elevation swath profiles (netCDF archive)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: ELEVATION_SWATH_PROFILES.nc

swath_landcover:
  description: |
    LandCover swath profiles (netCDF archive)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_SWATH_PROFILES_%(subset)s.nc

swath_valleybottom:
  description: |
    Valleybottom swath profiles (netCDF archive)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: VALLEYBOTTOM_SWATH_PROFILES.nc