tiled:
  description: |
    DEM Tiles
  type: raster
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: RGE5M.vrt
  tiles:
    tileset: landcover
    template: RGE5M_%(row)02d_%(col)02d
    extension: .tif

flow:
  description: |
    D8 Flow Direction, derived from DEM
  type: raster
  group: drainage
  status: final
  subdir: GLOBAL/DEM
  filename: FLOW_RGE5M.vrt
  tiles:
    tileset: landcover
    template: FLOW_RGE5M_%(row)02d_%(col)02d
    extension: .tif

acc:
  description: |
    Accumulation raster (drainage area),
    derived from D8 Flow Direction
  type: raster
  group: drainage
  status: final
  subdir: GLOBAL/DEM
  filename: ACC_RGE5M.vrt
  tiles:
    tileset: landcover
    template: ACC_RGE5M_%(row)02d_%(col)02d
    extension: .tif

outlets:
  description: |
    Tile outlets, grouped per target tile (row, col).
    (gid) identifies the tile of origin.
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  tiles:
    tileset: landcover
    template: OUTLETS_%(row)02d_%(col)02d_%(gid)03d
    extension: .geojson

outlets-glob:
  description: |
    Tile outlets, per target tile glob pattern
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  tiles:
    tileset: landcover
    template: OUTLETS_%(row)02d_%(col)02d_*
    extension: .geojson

inlets:
  description: |
    Tile flow inlets
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  tiles:
    tileset: landcover
    template: INLETS_%(row)02d_%(col)02d
    extension: .shp

inlets:
  description: |
    Tile flow inlets
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: INLETS.shp
  tiles:
    tileset: landcover
    template: INLETS_%(row)02d_%(col)02d
    extension: .shp

inlet-sources:
  description: |
    Cross-tile stream connections
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: SOURCES.shp
  tiles:
    tileset: landcover
    template: SOURCES_%(row)02d_%(col)02d
    extension: .shp

streams-from-sources:
  description: |
    Theoretical stream network, derived from DEM and mapped sources
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: RHTS_NOATTR.shp
  tiles:
    tileset: landcover
    template: RHTS_%(row)02d_%(col)02d
    extension: .shp

sources:
  description: |
    Theoretical stream network sources,
    with mapped sources attributes
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: RHTS_SOURCES.shp

streams-attr:
  description: |
    Theoretical stream network with network attributes
    (axis identifier, axis length, Hack and Strahler order)
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL/DEM
  filename: RHTS_ATTR.shp

streams-attr-sources:
  description: |
    Theoretical stream network
    with mapped sources attributes
  type: polygon
  subdir: GLOBAL/DEM
  filename: RHTS_ATTR_JOINED.shp

streams:
  description: |
    Theoretical stream network derived from DEM,
    with attributes from mapped river network
  type: polygon
  group: drainage
  status: final
  subdir: GLOBAL/DEM
  filename: RHTS.shp

streams-tiled:
  description: |
    Stream network aggregated by axis and tiles
  type: polygon
  group: drainage
  status: temporary
  subdir: GLOBAL
  filename: STREAMS.shp

landcover-default:
  description: |
    Default LandCover Tileset
  type: raster
  subdir: GLOBAL/LANDCOVER
  filename: LANDCOVER_2018.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_%(row)02d_%(col)02d
    extension: .tif

landcover-cesbio:
  description: |
    LandCover Tiles from CESBIO 2018,
    derived from Sentinel 2 annual classification
  type: raster
  subdir: GLOBAL/CESBIO
  filename: LANDCOVER_CESBIO_2018.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CESBIO_%(row)02d_%(col)02d
    extension: .tif

landcover-gpk:
  description: |
    LandCover Tiles from GeoPeka database,
    derived from BD Topo 2019 + RPG 2016
  type: raster
  subdir: GLOBAL/GEOPEKA
  filename: LANDCOVER_GEOPEKA_2019.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_GEOPEKA_2019_%(row)02d_%(col)02d
    extension: .tif

landcover-bdt:
  description: |
    LandCover Tiles from BD Topo 2019 + RPG 2016
    (direct rasterization)
  type: raster
  subdir: GLOBAL/BDTOPO
  filename: LANDCOVER_BDT_2019.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_BDT_2019_%(row)02d_%(col)02d
    extension: .tif

landcover-separate:
  description: |
    Land cover classe into separate contingency bands,
    used to calculate accumulated watershed metrics
  type: raster
  group: landcover
  status: temporary
  subdir: GLOBAL/LANDCOVER
  filename: LANDCOVER_CLASSES.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CLASSES_%(row)02d_%(col)02d
    extension: .tif

population:
  description: |
    Population (2015)
  type: raster
  subdir: GLOBAL/POPULATION
  filename: POP_2015.vrt
  tiles:
    tileset: landcover
    template: POP_2015_%(row)02d_%(col)02d
    extension: .tif

population-income:
  description: |
    Normalized Household Income (2015)
  type: raster
  subdir: GLOBAL/POPULATION
  filename: SNV_2015.vrt
  tiles:
    tileset: landcover
    template: SNV_2015_%(row)02d_%(col)02d
    extension: .tif

subgrid_mask:
  description: |
    SubGrid Mask
  type: raster
  subdir: SUBGRID
  filename: SUBGRID_MASK.tif

subgrid_outlets:
  description: |
    SubGrid Outlets
  type: point
  subdir: SUBGRID
  filename: SUBGRID_OUTLETS.shp

subgrid_graph:
  description: |
    SubGrid Topography Graph
  type: linestring
  subdir: SUBGRID
  filename: SUBGRID_GRAPH.shp

subgrid_population:
  description: |
    SubGrid Population
  type: raster
  subdir: SUBGRID
  filename: POP_2015.tif

subgrid_landcover:
  description: |
    SubGrid LandCover
  type: raster
  subdir: SUBGRID
  filename: LANDCOVER_2018.tif

subgrid_dominant_landcover:
  description: |
    SubGrid Dominant LandCover
  type: raster
  subdir: SUBGRID
  filename: LANDCOVER_DOMINANT_2018.tif

ax_tiles:
  description: |
    List of tiles intersecting given axis
  type: text
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TILES.csv

ax_talweg:
  description: |
    Mapped river network talweg (axis subset)
  type: linestring
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: TALWEG.shp

ax_refaxis:
  description: |
    Reference axis
  type: linestring
  group: spatial reference
  status: final
  subdir: AXES/AX%(axis)04d/REF
  filename: REFAXIS.shp

ax_drainage_network:
  description: |
    Theoretical stream network (axis subset)
  type: linestring
  group: drainage
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DRAINAGE.shp

ax_watershed:
  description: |
    Watershed delineation
  type: polygon
  group: drainage
  status: final
  subdir: AXES/AX%(axis)04d
  filename: WATERSHED.shp
  tiles:
    tileset: landcover
    template: WATERSHED_%(row)02d_%(col)02d
    extension: .shp

ax_flow_height:
  description: |
    Height above nearest drainage, following flow
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: FLOW_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: FLOW_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_flow_distance:
  description: |
    Distance to nearest drainage, following flow
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: FLOW_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: FLOW_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_axis_distance:
  description: |
    Distance to reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: AXIS_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: AXIS_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_axis_measure:
  description: |
    Distance (measure) along reference axis
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: AXIS_MEASURE.vrt
  tiles:
    tileset: landcover
    template: AXIS_MEASURE_%(row)02d_%(col)02d
    extension: .tif

ax_dgo:
  description: |
    Spatial units discretization
    TODO duplicate of ax_swaths, to be removed
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_dgo_parts:
  description: |
    Spatial units polygons, extracted from measure raster
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO_PARTS.shp
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .shp

ax_dgo_vector:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
    TODO duplicate of ax_swath_features, to be removed
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp

ax_swaths:
  description: |
    Spatial units discretization
  type: raster
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: DGO.vrt
  tiles:
    tileset: landcover
    template: DGO_%(row)02d_%(col)02d
    extension: .tif

ax_swath_features:
  description: |
    Spatial units polygons,
    after cross-tile merge and invalid parts removal
  type: polygon
  group: spatial reference
  status: temporary
  subdir: AXES/AX%(axis)04d/REF
  filename: DGO.shp

ax_nearest_distance:
  description: |
    Distance to nearest drainage
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: NEAREST_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: NEAREST_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_nearest_height:
  description: |
    Height above nearest drainage (HAND)
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: NEAREST_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: NEAREST_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_relative_elevation:
  description: |
    Height above nearest drainage (HAND)
    TODO duplicate of ax_nearest_height, to be removed
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: NEAREST_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: NEAREST_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_distance:
  description: |
    Distance to mapped talweg
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TALWEG_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: TALWEG_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_talweg_height:
  description: |
    Height above mapped talweg
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: TALWEG_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: TALWEG_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_valley_bottom:
  description: |
    Valley bottom extended to topographic limits
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_BOTTOM.vrt
  tiles:
    tileset: landcover
    template: VALLEY_BOTTOM_%(row)02d_%(col)02d
    extension: .tif

ax_valley_distance:
  description: |
    Valley bottom extended to topographic limits
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: VALLEY_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_refaxis_valley_profile:
  description: |
    Valley floor elevation profile
  type: netcdf
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d/METRICS
  filename: REFAXIS_VALLEY_PROFILE.nc

ax_valley_height:
  description: |
    Height above valley floor
  type: raster
  group: metrology
  status: final
  subdir: AXES/AX%(axis)04d
  filename: VALLEY_HEIGHT.vrt
  tiles:
    tileset: landcover
    template: VALLEY_HEIGHT_%(row)02d_%(col)02d
    extension: .tif

ax_continuity:
  description: |
    Landcover continuity map
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: LANDCOVER_CONTINUITY.vrt
  tiles:
    tileset: landcover
    template: LANDCOVER_CONTINUITY_%(row)02d_%(col)02d
    extension: .tif

ax_continuity_variant:
  description: |
    Landcover continuity map (Variants)
  type: raster
  group: corridor
  status: final
  subdir: AXES/AX%(axis)04d
  filename: LANDCOVER_CONTINUITY_%(variant)s.tif

ax_swath_elevation:
  description: |
    Elevation swath
  type: npz
  subdir: AXES/AX%(axis)04d/SWATH/ELEVATION
  filename: SWATH_ELEVATION_%(gid)04d.npz

ax_swath_landcover:
  description: |
    Landcover swath
  type: npz
  subdir: AXES/AX%(axis)04d/SWATH/LANDCOVER
  filename: SWATH_ELEVATION_%(gid)04d_%(subset)s.npz

ax_swath_axes:
  description: |
    Spatial unit (swath) distance axis
    (orthogonal to reference axis)
  type: linestring
  subdir: AXES/AX%(axis)04d/REF
  filename: SWATH_AXIS.shp

ax_buffer_mask:
  description: |
    Buffer area calculated from axis active channel,
    based on landcover continuity classes.
    1 = active channel
    2 = buffer area within buffer width from active channel
    0 = elsewhere
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_MASK.vrt
  tiles:
    tileset: landcover
    template: BUFFER_MASK_%(row)02d_%(col)02d
    extension: .tif

ax_buffer_distance:
  description: |
    Distance from axis active channel,
    based on landcover continuity classes
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_DISTANCE.vrt
  tiles:
    tileset: landcover
    template: BUFFER_DISTANCE_%(row)02d_%(col)02d
    extension: .tif

ax_buffer_profile:
  description: |
    Discrete spatial units (ie. slices of buffer area)
    along reference axis
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: BUFFER_PROFILE.vrt
  tiles:
    tileset: landcover
    template: BUFFER_PROFILE_%(row)02d_%(col)02d
    extension: .tif

ax_subgrid_profile:
  description: |
    SubGrid Profile
  type: point
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SUBGRID_PROFILE.shp

ax_subgrid_watershed:
  description: |
    SubGrid Profile Sample Watershed
  type: raster
  group: metrology
  status: temporary
  subdir: AXES/AX%(axis)04d
  filename: SUBGRID_WATERSHED.vrt
  tiles:
    tileset: landcover
    template: SUBGRID_WATERSHED_%(row)02d_%(col)02d
    extension: .tif

ax_swath_elevation_pack:
  description: |
    Elevation Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: ELEVATION_SWATH_PROFILES.nc

ax_swath_landcover_pack:
  description: |
    LandCover Swath Profiles NetCDF Archive
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_SWATH_PROFILES_%(subset)s.nc

metrics_fcw:
  description: |
    Fluvial Corridor Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: FLUVIAL_CORRIDOR_WIDTH.nc

metrics_lcw:
  description: |
    LandCover Width
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH.nc

metrics_lcw_variant:
  description: |
    LandCover Width (Variants)
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: LANDCOVER_WIDTH_%(variant)s.nc

metrics_watershed:
  description: |
    Watershed Metrics
  type: netcdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/METRICS
  filename: WATERSHED_%(subset)s.nc

pdf_ax_swath_elevation:
  description: |
    Elevation swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_swath_landcover:
  description: |
    Landcover swath output, per spatial unit
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER/SWATH
  filename: SWATH_ELEVATION_%(gid)04d_%(kind)s.pdf

pdf_ax_landcover_profile:
  description: |
    Landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LANDCOVER_PROFILE_%(variant)s.pdf

pdf_ax_leftright_profile:
  description: |
    Left bank/right bank landcover longitudinal profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/LANDCOVER
  filename: LEFTRIGHT_PROFILE_%(variant)s.pdf

pdf_ax_watershed_profile:
  description: |
    Watershed Profile
  type: pdf
  group: metrics
  status: final
  subdir: AXES/AX%(axis)04d/PDF/WATERSHED
  filename: WATERSHED_PROFILE_%(variable)s_W%(width).0f.pdf
